## YAML Template.
---

server:
    port: 8282

spring:
    datasource:
      url: jdbc:postgresql://localhost:8745/${E_DB_DATABASE_HML}
      username: postgres
      password: ${E_DB_PASSWORD_HML}
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          package-to-scan: br.com.deltatgn.endereco.infrastructure.entities
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
    cloud:
      loadbalancer:
        ribbon:
        enable: true
