## YAML Template.
---

server:
  port: 8181

spring:
  datasource:
    url: jdbc:h2:mem:apoioweb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        package-to-scan: br.com.deltatgn.endereco.infrastructure.entities
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.H2Dialect
  cloud:
    loadbalancer:
      ribbon:
        enable: true
  h2:
    console:
      enabled: true
      path: /h2-console
